from data_cleanup import *
import matplotlib.pyplot as plt
from fpdf import FPDF

'''
Favor Analysis
By Gabriela De La Torre
2019/07/11 
Parameters: Date range in yyyy/mm/dd_yyyy/mm/dd format, used to title the pdf
Purpose: Takes the files given by favor and cleans the data to be printed to a pdf
Output: A formatted pdf report that has been approved by Rob and Rick
Notes: Due to favor reports not adding the stores with zero sales you still have to manually add in that location, and
zero out the revenue in the store column  
'''
fig1 = plt.pie(BM_orders, labels=bm_store_num_dict, autopct='%1.1f%%', textprops={'fontsize': 12})
plt.title('BM Orders')
plt.savefig('Figure_1.png')


fig2 = plt.pie(LM_orders, labels=lm_store_num_dict, autopct='%1.1f%%', textprops={'fontsize': 12})
plt.title('LM Orders')
plt.savefig('Figure_2.png')


# change the pie chart to a bar graph for cleaner representation
fig3 = plt.bar(total_store_num_dict, Total_orders)
plt.title('Total Orders')
plt.savefig('Figure_3.png')


fig4 = plt.pie(BM_revs, labels=bm_store_num_dict, autopct='%1.1f%%', textprops={'fontsize': 12})
plt.title('BM Sales')
plt.savefig('Figure_4.png')


fig5 = plt.pie(LM_revs, labels=lm_store_num_dict, autopct='%1.1f%%', textprops={'fontsize': 12})
plt.title('LM Sales')
plt.savefig('Figure_5.png')


# change the pie chart to a bar graph for cleaner representation
fig6 = plt.bar(total_store_num_dict, Total_sales)
plt.title('Total Sales')
plt.savefig('Figure_6.png')


pdf = FPDF(orientation='L')
pdf.add_page()
pdf.set_xy(5, 0)
pdf.set_font('arial', '', 15)
pdf.cell(20, 10, 'Favor Report', ln=2)
pdf.image('Figure_1.png', x=70, y=0, w=95, h=70)
pdf.image('Figure_4.png', x=155, y=0, w=95, h=70)
pdf.image('Figure_2.png', x=70, y=65, w=95, h=70)
pdf.image('Figure_5.png', x=155, y=65, w=95, h=70)

pdf.set_font('arial', '', 10)
pdf.cell(w=55, h=8, txt='Gross Revenue: $' + str(revenue_number), ln=2, align='L', border='LRT')
pdf.cell(55, 8, 'Favor Commission: $' + str('%.2f' % (favor_com)), ln=2, align='L', border='RL')
pdf.cell(55, 8, 'Revenue: $' + str(our_rev), ln=2, align='L', border='RLB')
pdf.set_xy(5, 42)
pdf.cell(13, 5, 'Store', border='B')
pdf.cell(16, 5, 'Orders', border='B')
pdf.cell(19, 5, ' Sales', ln=2, border='B')
pdf.set_xy(5, 47)
pdf.cell(28, 5, ' #16{:^20}'.format(str(int(orders_per_store['#16'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #17{:^20}'.format(str(int(orders_per_store['#17'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #19{:^20}'.format(str(int(orders_per_store['#19'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #21{:^20}'.format(str(int(orders_per_store['#21'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #35{:^20}'.format(str(int(orders_per_store['#35'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #64{:^20}'.format(str(int(orders_per_store['#64'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #65{:^20}'.format(str(int(orders_per_store['#65'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #81{:^20}'.format(str(int(orders_per_store['#L1'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #82{:^20}'.format(str(int(orders_per_store['#L2'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #83{:^20}'.format(str(int(orders_per_store['#L3'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #84{:^20}'.format(str(int(orders_per_store['#L4'].sum()))), ln=2, align='L')
pdf.cell(28, 5, ' #85{:^20}'.format(str(int(orders_per_store['#L5'].sum()))), ln=2, align='L')
pdf.set_xy(33, 47)

pdf.cell(15, 5, '$' + str(round(revenue_per_store['#16'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#17'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#19'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#21'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#35'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#64'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#65'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#L1'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#L2'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#L3'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#L4'].sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(revenue_per_store['#L5'].sum(), 2)), ln=2, align='L')
pdf.set_xy(5, 110)
pdf.cell(28, 5, ' BM{:^20}'.format(str(int(BM_orders.sum()))), ln=2, align='L')
pdf.cell(28, 5, ' LM{:^20}'.format(str(int(LM_orders.sum()))), ln=2, align='L')
pdf.cell(28, 5, ' ALL{:^18}'.format(str(int(LM_orders.sum() + BM_orders.sum()))), ln=2, align='L')
pdf.set_xy(33, 110)
pdf.cell(15, 5, '$' + str(round(BM_revs.sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(round(LM_revs.sum(), 2)), ln=2, align='L')
pdf.cell(15, 5, '$' + str(revenue_number), ln=2, align='L')
pdf.set_xy(5, 130)
pdf.cell(285, 5, ' Order Details *Wait Time is @ Merchant', ln=2, border='B')
pdf.set_font('arial', '', 9.5)
pdf.set_xy(5, 135)
pdf.cell(50, 5, '{}{:^18}{:^18}{:^18}{:^18}{:^18}{:^18}{:^18}{:^18}{:^18}{:^18}'.format('Store', 'Avg ItemsCost',
                                                                                        'Avg Commission',
                                                                                        'Avg Driver Rating',
                                                                                        'Avg Items Rating',
                                                                                        'Avg Wait Time*',
                                                                                        'Med ItemsCost',
                                                                                        'Med Commission',
                                                                                        'Med Driver Rating',
                                                                                        'Med Items Rating',
                                                                                        'Med Wait Time*'), ln=2)

pdf.cell(43, 5, '{:^5}{:^26}'.format('#16', '$' + str(round(store16_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#17', '$' + str(round(store17_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#19', '$' + str(round(store19_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#21', '$' + str(round(store21_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#35', '$' + str(round(store35_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#64', '$' + str(round(store64_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#65', '$' + str(round(store65_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format(' BM', '$' + str(round(BM_Items_mean, 2))), ln=2)
pdf.set_xy(48, 140)
pdf.cell(20, 5, '$' + str(round(store16_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store17_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store19_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store21_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store35_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store64_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store65_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(BM_Com_mean, 2)), ln=2)
pdf.set_xy(75, 140)
pdf.cell(20, 5, str(round(store16_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store17_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store19_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store21_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store35_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store64_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store65_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(BM_Runner_mean, 2)), ln=2)
pdf.set_xy(105, 140)
pdf.cell(20, 5, str(round(store16_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store17_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store19_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store21_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store35_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store64_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store65_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(BM_Rating_mean, 2)), ln=2)
pdf.set_xy(130, 140)
pdf.cell(20, 5, str(round(store16_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store17_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store19_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store21_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store35_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store64_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store65_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(BM_Time_mean, 2)), ln=2)
pdf.set_xy(158, 140)
pdf.cell(20, 5, '$' + str(round(store16_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store17_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store19_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store21_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store35_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store64_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store65_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(43, 5, '$' + str(round(BM_Items_median, 2)), ln=2)
pdf.set_xy(185, 140)
pdf.cell(20, 5, '$' + str(round(store16_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store17_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store19_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store21_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store35_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store64_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(store65_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(BM_Com_median, 2)), ln=2)
pdf.set_xy(215, 140)
pdf.cell(20, 5, str(round(store16_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store17_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store19_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store21_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store35_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store64_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store65_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(BM_Runner_median, 2)), ln=2)
pdf.set_xy(245, 140)
pdf.cell(20, 5, str(round(store16_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store17_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store19_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store21_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store35_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store64_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store65_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(BM_Rating_median, 2)), ln=2)
pdf.set_xy(270, 140)
pdf.cell(20, 5, str(round(store16_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store17_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store19_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store21_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store35_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store64_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(store65_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(BM_Time_median, 2)), ln=2)
pdf.add_page()
pdf.set_xy(5, 5)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#L1', '$' + str(round(storeL1_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#L2', '$' + str(round(storeL2_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#L3', '$' + str(round(storeL3_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#L4', '$' + str(round(storeL4_d['Items Cost'].mean(skipna=True), 2))), ln=2)
pdf.cell(43, 5, '{:^5}{:^26}'.format('#L5', '$' + str(round(storeL5_d['Items Cost'].mean(skipna=True), 2))), ln=2)

pdf.cell(43, 5, '{:^5}{:^26}'.format(' LM', str(round(LM_Items_mean, 2))), ln=2)
pdf.set_xy(48, 5)
pdf.cell(20, 5, '$' + str(round(storeL1_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL2_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL3_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL4_d['Commission'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL5_d['Commission'].mean(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Com_mean, 2)), ln=2)
pdf.set_xy(75, 5)
pdf.cell(20, 5, str(round(storeL1_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL2_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL3_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL4_d['Runner Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL5_d['Runner Rating'].mean(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Runner_mean, 2)), ln=2)
pdf.set_xy(105, 5)
pdf.cell(20, 5, str(round(storeL1_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL2_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL3_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL4_d['Item Rating'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL5_d['Item Rating'].mean(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Rating_mean, 2)), ln=2)
pdf.set_xy(130, 5)
pdf.cell(20, 5, str(round(storeL1_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL2_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL3_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL4_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL5_d['Time at Merchant'].mean(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Time_mean, 2)), ln=2)
pdf.set_xy(158, 5)
pdf.cell(20, 5, '$' + str(round(storeL1_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL2_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(43, 5, '$' + str(round(storeL3_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(43, 5, '$' + str(round(storeL4_d['Items Cost'].median(skipna=True), 2)), ln=2)
pdf.cell(43, 5, '$' + str(round(storeL5_d['Items Cost'].median(skipna=True), 2)), ln=2)

pdf.cell(43, 5, str(round(LM_Items_median, 2)), ln=2)
pdf.set_xy(185, 5)
pdf.cell(20, 5, '$' + str(round(storeL1_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL2_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL3_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL4_d['Commission'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, '$' + str(round(storeL5_d['Commission'].median(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Com_median, 2)), ln=2)
pdf.set_xy(215, 5)
pdf.cell(20, 5, str(round(storeL1_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL2_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL3_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL4_d['Runner Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL5_d['Runner Rating'].median(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Runner_median, 2)), ln=2)
pdf.set_xy(245, 5)
pdf.cell(20, 5, str(round(storeL1_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL2_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL3_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL4_d['Item Rating'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL5_d['Item Rating'].median(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Rating_median, 2)), ln=2)
pdf.set_xy(270, 5)
pdf.cell(20, 5, str(round(storeL1_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL2_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL3_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL4_d['Time at Merchant'].median(skipna=True), 2)), ln=2)
pdf.cell(20, 5, str(round(storeL5_d['Time at Merchant'].median(skipna=True), 2)), ln=2)

pdf.cell(20, 5, str(round(LM_Time_median, 2)), ln=2)

pdf.image('Figure_6.png', x=40, y=40, w=110, h=85)
pdf.image('Figure_3.png', x=150, y=40, w=110, h=85)

filename = input('Enter date range for report: ex.yyyy/mm/dd_yyyy/mm/dd\n')
pdf.output(filename + '-favor.pdf', 'F')
